### ISSUE TITLE
help - F2 and F3 keys 

### ISSUE THREAD

**Issue by InGearX** [sharat87/keyboard-fu#1]
I love keyboard-fu
thank you

but I can not get F2 and F3 to work for me to do 

fu.tabNext() and fu.tabPrevious()

see http://screenshooter.net/4116984/amwvyqp

please test this, how can we all address this?

if you could email me at [gmail] user "wpb317" in any case...

thank you so much! awaiting...

**Comment by sharat87** [comment]
Seems to work fine at my end. Please not that these keys won't work on extensions' options pages and the like. Also, your changes to hotkeys take effect only if you refresh the tabs. Can you recheck with these in mind?
