### ISSUE TITLE
Windows openBookmarkByPath unable to locate any bookmarks

### ISSUE THREAD

**Issue by timvisher** [sharat87/keyboard-fu#2]
Hi sharat,

This is a fantastic plugin. I'm using it full time on my Mac and it's wonderful.

On my Windows box, though, I'm getting undefined errors for any definition of an `openBookmarkByPath` hotkey.

For instance

I have a bookmarklet: `/Bookmarks Bar/quix…` and a keyboard-fu shortcut `z1` defined as:

```
fu.openBookmarkByPath('/Bookmarks Bar/quix…', target='here')
```

and when I execute `z1` I get 3 alert boxes all telling me that bookmark `undefined` cannot be found/does not exist/no valid url etc.

It doesn't appear to be a problem with the unicode in the bookmark name as it works fine on my mac.

None of the bookmarks defined in this way work. And they all work on my Mac.

If you need anything else, let me know!

**Comment by sharat87** [comment]
Hey, thanks for dropping by. I'm glad you use it full time :)

I'm currently not in a position to work on this, and am anticipating
my new laptop. I will be able to look further only after that happens
(should be less than a week). I'm just dropping this email so you
know. I hope this is okay.

In the mean time, can you confirm if the chrome versions are the same
on your mac and windows and if the bookmarklets work find if clicked
on them?

Thanks again.

## 

Shrikant Sharat Kandula, on his iPad.

On 29-Jun-2012, at 7:49 PM, Tim Visher
reply@reply.github.com
wrote:

**Comment by timvisher** [comment]
On Fri, Jun 29, 2012 at 10:46 AM, Shrikant Sharat
reply@reply.github.com
wrote:

> I'm currently not in a position to work on this, and am anticipating
> my new laptop. I will be able to look further only after that happens
> (should be less than a week). I'm just dropping this email so you
> know. I hope this is okay.

No problem. It's not the end of the world. :)

> In the mean time, can you confirm if the chrome versions are the same
> on your mac and windows and if the bookmarklets work find if clicked
> on them?

I can confirm that all the bookmarks work when clicked.

Windows Version is: 19.0.1084.56 m

I'll report later on the Mac.

Thanks!

**Comment by timvisher** [comment]
I don't use this software anymore. :(
